services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_ADMIN_SERVER_PORT: 8081  # Establece el puerto para la interfaz de administración

    ports:
      - "2181:2181"
    networks:
      - adrius-network

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - adrius-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db-test-sofka
      POSTGRES_USER: adrius
      POSTGRES_PASSWORD: 123456789@
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adrius-network

  microservice-persons:
    #platform: linux/arm64
    build:
      context: ./microservice-persons  # Directorio donde está el Dockerfile de microservice-persons
    container_name: microservice-persons
    image: microservice-persons:1.0.0
    ports:
      - "8001:8001"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      KAFKA_BROKER: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db-test-sofka
      SPRING_DATASOURCE_USERNAME: adrius
      SPRING_DATASOURCE_PASSWORD: 123456789@
    depends_on:
      - kafka #Con esto se asegura que kafka esté levantado antes de levantar microservice-persons
      - postgres
    networks:
      - adrius-network

  microservice-accounts:
    #platform: linux/arm64
    build:
      context: ./microservice-accounts  # Directorio donde está el Dockerfile de microservice-accounts
    container_name: microservice-accounts
    image: microservice-accounts:1.0.0
    ports:
      - "8002:8002"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      KAFKA_BROKER: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db-test-sofka
      SPRING_DATASOURCE_USERNAME: adrius
      SPRING_DATASOURCE_PASSWORD: 123456789@
    depends_on:
      - kafka #Con esto se asegura que kafka esté levantado antes de levantar microservice-accounts
      - postgres
    networks:
      - adrius-network

volumes:
  postgres_data:

networks:
  adrius-network:
    driver: bridge
